Feature+Fix: two Issues in character generation and homeland feature
fvtt-fria-ligan/forbidden-lands-foundry-vtt pull request #332
Opened 2023-05-19 08:57 UTC by sebastiansIT

1. Add i18n-Labels to generation of notes for generated characters (Childhood and Formative Events)
2. Change all datasets for char gen. Consumables are now index based instead of Dice-Based. This is necessary because the systems values for consumables are defined as 1=D6, 2=D8, 3=D10 and 4=D12. The old values 6,8,10,12 doesn't work in the actual Version of the System.
3. Add the optional random selection of a homeland region and write it to the generated note. I adopted this from the German version of "Legends & Adventurers"

2023-05-24 18:56 UTC, aMediocreDad commented
I don't see the actual homelands added in the German dataset. Is this intentional?

2023-05-24 18:59 UTC, aMediocreDad requested changes
Small change for English localization string. I am also interested in knowing how this homeland thing works, seeing as it is only in the German-language version?

2023-05-24 18:59 UTC, aMediocreDad commented on src/components/character-generator/character-converter.js
> +			notes += `<h3>${game.i18n.localize("FLCG.EVENT")}: ${event.name}</h3><p>${event.description}</p>`;
Thank you for finding and removing hardcoded language strings.

2023-05-24 18:59 UTC, aMediocreDad commented on static/assets/datasets/chargen/dataset-de.json
Big thanks for this too!

2023-05-24 18:59 UTC, aMediocreDad commented on static/lang/en.json
> +	"FLCG.HOMELAND": "You comes from",
```suggestion
	"FLCG.HOMELAND": "You hail from",
```

2023-05-25 05:17 UTC, sebastiansIT commented
> I don't see the actual homelands added in the German dataset. Is this intentional?

I have a personal version for bitter reach and added it to this data set. For the base game I only have a german printed version of Legends & Adventurers but I can transfer it to the german default dataset if you want.

It ist only an Array of Strings for each kin like this: "homeland": ["Northfall", "Northfall", "Silver Coast", "Silver Coast", "Silver Coast", "Raven Land"],

2023-05-25 05:33 UTC, aMediocreDad commented
> For the base game I only have a german printed version of Legends & Adventurers but I can transfer it to the german default dataset if you want.

That'd be great!

2023-05-25 05:34 UTC, aMediocreDad commented
Also, just to be clear. This issue #331 is not fixed in this PR?

2023-05-25 05:46 UTC, sebastiansIT commented
> Also, just to be clear. This issue #331 is not fixed in this PR?

No, it isn't. There are two possible solutions and I don't want to decide which one is the best.

2023-05-25 06:01 UTC, sebastiansIT commented
> > For the base game I only have a german printed version of Legends & Adventurers but I can transfer it to the german default dataset if you want.
> 
> That'd be great!

Done! But your Pull Request Liniting is failed for this commit.

2023-05-25 15:09 UTC, aMediocreDad approved these changes

2023-05-25 15:25 UTC, merged