Update pt-br.json
fvtt-fria-ligan/forbidden-lands-foundry-vtt pull request #96
Opened 2021-04-19 19:15 UTC by franklinbenini

localization pt-br.json updated to 5.1.1

2021-04-20 07:20 UTC, narukaioh commented
the portuguese it's fine, but I will review the changes in local

2021-04-22 09:05 UTC, aMediocreDad requested changes

2021-04-22 09:05 UTC, aMediocreDad commented on src/lang/pt-br.json
> -	"ATTRIBUTE.AGILITY": "Agilidade",
The attributes should not be all caps. If they are the main tab on the character sheet will overflow and scroll as a result.

2021-04-22 09:06 UTC, aMediocreDad requested changes
Please fix the lines in the comment above.

2021-04-22 09:06 UTC, aMediocreDad commented on src/lang/pt-br.json
> -	"ATTRIBUTE.WITS": "Astúcia",
The attributes should not be all caps. If they are the main tab on the character sheet will overflow and scroll as a result.

2021-04-22 09:08 UTC, aMediocreDad requested changes

2021-04-22 09:08 UTC, aMediocreDad commented on src/lang/pt-br.json
> +  "ATTRIBUTE.WITS": "ASTÚCIA",
The attributes should not be all caps. If they are the main tab on the character sheet will overflow and scroll as a result.

2021-04-22 11:03 UTC, franklinbenini reviewed
fixed attributes caps

2021-04-22 15:43 UTC, aMediocreDad approved these changes
Thanks! I'll go ahead and merge this.

2021-04-22 15:44 UTC, merged